### PR TITLE
Problem: webhook module is hogging the webserver

### PR DESCRIPTION
**Pull request by the-maldridge**
See commit for more details.

### CODE REVIEW

**Comment by the-maldridge** [comment]
Worth noting that this has breaking config changes.

**Comment by Vaelatern** [comment]
I'm not sure this is a problem that needs solving. The general changes are where the code will go, but I don't see the problem it fixes now. I don't buy that we can't make the changes later when the httpd needs to do more.

**Comment by the-maldridge** [comment]
In general I would advise against trying to make sweeping architectural changes (which separating the webserver clearly qualifies as) after significant code has been written.  As this is written the http code is now modular and reusable and can be dropped into every daemon to provide the infrastructure to serve a status page.  As previously written you would need more hacky singletons to achieve the same effect outside the dxpbd application.

**Comment by Vaelatern** [comment]
A similar rework has been done now, because of the need to add monitoring, though not in all the same ways as this PR would have done.

I appreciate the work, and did reference it while writing the version that ended up in the tree.

**Pull request closed without merging**
